import type { Metadata } from "next";
import "./globals.css";
import '@repo/ui/styles.css'
import { NotificationProvider } from "../Component/notification";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={` `}>
      <NotificationProvider>
        {children}
      </NotificationProvider>
      </body>
    </html>
  );
}
